// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7i8Rog3VjpZDwJlQR0sR1Nrnnoj1exoE',
    appId: '1:195508371805:web:0c6573b238293a878a28b4',
    messagingSenderId: '195508371805',
    projectId: 'live-tracking-57f37',
    authDomain: 'live-tracking-57f37.firebaseapp.com',
    storageBucket: 'live-tracking-57f37.appspot.com',
    measurementId: 'G-X02K925C31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxiXLuxHwprIGC4AVOpEYN9QgHi8C7yak',
    appId: '1:195508371805:android:d3fdebb9757d6c908a28b4',
    messagingSenderId: '195508371805',
    projectId: 'live-tracking-57f37',
    storageBucket: 'live-tracking-57f37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIjG9dEV6sPlBEuTrt_YJuCUvV45gtgyY',
    appId: '1:195508371805:ios:b5c17f7aab00e25a8a28b4',
    messagingSenderId: '195508371805',
    projectId: 'live-tracking-57f37',
    storageBucket: 'live-tracking-57f37.appspot.com',
    iosBundleId: 'com.example.foodOrderTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIjG9dEV6sPlBEuTrt_YJuCUvV45gtgyY',
    appId: '1:195508371805:ios:c92434ad16584d268a28b4',
    messagingSenderId: '195508371805',
    projectId: 'live-tracking-57f37',
    storageBucket: 'live-tracking-57f37.appspot.com',
    iosBundleId: 'com.example.foodOrderTracking.RunnerTests',
  );
}
